### ISSUE TITLE
Questions about Library Version

### ISSUE THREAD

**Issue by seonhoon1002** [MCG-NJU/DEQDet#2]
Hello, I've traveled your code and paper these day

And I appreciate sharing your code.

But I have a question about library versions of pytorch, mmcv, mmdet or etc.

Because I have a compatibility problem.

Thank you.

**Comment by HELLORPG** [comment]
Maybe in #1 , [here](https://github.com/MCG-NJU/DEQDet/issues/1#issuecomment-1810705597).

**Comment by seonhoon1002** [comment]
In my case mmcv and mmdet are problems, but I can solve them by installing mmdet from the github repository.
Thank you
